name: OCL Validation
'on':
  workflow_dispatch: {}
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore Dependencies
        run: npm install
        shell: bash
        working-directory: ocl_pr
      - name: Validate OCL
        run: node ocl_pr/check.js .octopus/project
        shell: bash